FROM ubuntu:latest AS builder
RUN apt-get update
RUN apt install -y build-essential wget git  automake autotools-dev  libtool zlib1g zlib1g-dev libexif-dev  python3 python3-pip python3-dev libssl-dev \
cmake clang meson ninja-build afl
WORKDIR /
RUN git clone https://github.com/rizinorg/rizin.git
WORKDIR /rizin
RUN CC=afl-clang CXX=afl-clang++ meson build .
RUN ninja -C build
RUN ninja -C build install
RUN mkdir /rizinCorpus
RUN cp /usr/bin/whoami /rizinCorpus
RUN cp /usr/bin/echo /rizinCorpus
#RUN cp /usr/bin/xxd /rizinCorpus
RUN cp /usr/bin/grep /rizinCorpus
ENV LD_LIBRARY_PATH=/usr/local/lib

FROM fuzzers/afl:2.52
COPY --from=builder /usr/local/bin/rizin ./
COPY --from=builder /rizinCorpus /rizinCorpus
ENTRYPOINT ["afl-fuzz", "-i", "/rizinCorpus", "-o", "/rizinOut", "-m", "2048"]
CMD ["./rizin", "@@"]
